### ISSUE TITLE
Minor bugs

### ISSUE THREAD

**Issue by satyaborg** [MonashDataFluency/python-web-scraping#13]
Under the **Legal and Ethical Considerations**:
- The 2nd link from references appears to be broken
- Typo: **available** as **avaialable**

Also need to make all the links directly clickable e.g. [zyxware](https://www.zyxware.com/articles/5914/list-of-fortune-500-companies-and-their-websites-2018)

**Comment by pansapiens** [comment]
The 'members of parliament' case study (2nd link) is [still available on the Wayback Machine](https://web.archive.org/web/20190215161212/naelshiab.com/members-parliament-web-scraping/), but probably better to find an alternative.

**Comment by naveenkaushik2504** [comment]
I think I might put this [one](https://www.analyticsvidhya.com/blog/2017/07/web-scraping-in-python-using-scrapy/). Explains scrapy in a good basic way for readers to get started. Just trying to avoid links from websites who have web scraping as their main business.  

Feel free to add any other good ones to the list or comment here.
