### ISSUE TITLE
Legal and ethical section

### ISSUE THREAD

**Issue by naveenkaushik2504** [MonashDataFluency/python-web-scraping#2]
As of now the `Legal and Ethical Considerations` section is at the end of the course. There have been suggestions on moving this to the first to keep the web scraping principles in mind. 
Opening this issue to discuss and hear thoughts.

**Comment by pansapiens** [comment]
It's an important section but I think it's fine (and best) to leave it at the end of the course. These are practical hands-on courses, and the legal and ethical section is not very hands-on (although it might become group discussion oriented). I think it would set the wrong tone at the beginning of the workshop to not dive into coding quickly.

Also, the fact that participants can see it in the table of contents and know it's coming will give them time to think about it in relation to their own projects, and have interesting discussion by the time that section arrives. The added advantage of having this at the end is that it keeps the discussion time-bounded.

**Comment by naveenkaushik2504** [comment]
Keeping it the same as of now, at least for the first iteration of the workshop.
