### ISSUE TITLE
Section 0 Intro Dictionary challenge redefines builtin `dict`

### ISSUE THREAD

**Issue by pansapiens** [MonashDataFluency/python-web-scraping#7]
In the dictionary challenge in https://github.com/MonashDataFluency/python-web-scraping/blob/master/notebooks/section-0-brief-python-refresher.ipynb 

The line `dict = {1:'a', 2:'b', 3:'c', 4:'d', 5:'e'}` redefines the builtin `dict()` function, which could cause issues later in the notebook (and is generally a bad idea).

**Comment by naveenkaushik2504** [comment]
Its a stale issue now as we have removed this part from the intro section. Look at issue #8 changes for the updates.
