### ISSUE TITLE
Section 0 - A (brief) Python refresher

### ISSUE THREAD

**Issue by satyaborg** [MonashDataFluency/python-web-scraping#8]
#### TODOs based on the feedback :
- Remove the basic Python concepts (from `Strings` to `Functions`)
- Expand on the more web-scraping relevant concepts such as : `dataframes`, `csv`, `json` and `regex`
- Change example for `regex` from HTML to a more generic string-based one  
- Include examples for each section that highlights how it would be useful in the context of web-scraping

#### Suggestions :
- Include a section on setting up Jupyter notebooks on Colab. Also a rundown of code+markdown, execution of cells etc.
- Include one mini challenge for each of the above sections
- Simplify everything!

**Comment by naveenkaushik2504** [comment]
@pansapiens @syborg91 @tarunbonu thoughts on the changes in this section? The best view would be directly looking at the website.

**Comment by syborg91** [comment]
@naveenkaushik2504 I think its much better and streamlined now. The topics are dealing with things most relevant to the workshop. 

A minor suggestion:  We can embed a "open in colab button" in every section (on the website) for ease of transition between site/notebooks, particularly for people new to colab.

**Comment by naveenkaushik2504** [comment]
Great suggestion. Done for the relevant notebooks.

**Comment by pansapiens** [comment]
@naveenkaushik2504 The _Open in Colab_ svg buttons were broken images for me due to my ad blocker(s). Might be worth hosting a static copy of the `colab-badge.svg` in the repo in case it effects others.

**Comment by pansapiens** [comment]
The quick intro to Pandas is good, very concise but covers lots of the basics.

It might be worth noting in the text that JSON is a string that can be turned into ('deserialized') a Python dictionary containing just primitive types (floats, strings, bools, lists, dicts and None).

I think the regex section is still going to be too much for some beginners in the time available, so maybe make note that "This is a whirlwind tour of regular expressions so you have some familiarity, but becoming proficient will require further study and practise. Regex is deep enough to have a whole workshop of it's own".

**Comment by naveenkaushik2504** [comment]
Incorporated the suggested changes.
